### ISSUE TITLE
После установки не работают "Быстрые отличия"

### ISSUE THREAD

**Issue by KovAlexey** [bia-technologies/edt-test-runner#3]
После установки плагина около номеров строк перестают работать "Быстрые отличия" (с файлом на диске\с гитом).
После удаления строки снова начинают отмечаться соответствующим цветом.
EDT 2022.1.2

**Comment by KovAlexey** [comment]
![изображение](https://user-images.githubusercontent.com/16429518/204983353-478779ed-03ff-422a-a337-65597b0f1771.png)

Речь идет про вот это. С установленным плагином отметки пропадают 
![изображение](https://user-images.githubusercontent.com/16429518/204983353-478779ed-03ff-422a-a337-65597b0f1771.png)

**Comment by theshadowco** [comment]
видать плагины конфликтуют, спасибо, не обращали внимание

**Comment by alkoleft** [comment]
Об этих "Быстрых изменения" идет речь?
![image](https://user-images.githubusercontent.com/13838250/212174291-51ed582f-9fcc-4826-b483-70c6dca87306.png)

Проверил на 2х версиях EDT (2021.3.4, 2022.2.2) в WIndos и Linux.
Проблема не воспроизвелась

**Comment by KovAlexey** [comment]
В течение недели постараюсь обновить ЕДТ и проверить.
Если все будет ок - отпишусь

**Comment by KovAlexey** [comment]
А попробуйте переоткрыть модуль с такими изменениями.
У меня до переоткрытия все работает.

Потом сохранить, закрыть, открыть и изменения уже не показываются

**Comment by KovAlexey** [comment]
Показ изменений настроен по "ревизии Git"

**Comment by KovAlexey** [comment]
Перед сохранением\после сохранения до закрытия редактора.
![изображение](https://user-images.githubusercontent.com/16429518/216898436-c0f177d4-ffe9-4f4f-a404-da0cddd0455b.png)

После сохранения и открытия

![изображение](https://user-images.githubusercontent.com/16429518/216898703-c0c28b1e-d9f7-479b-b141-b461fa12507a.png)

Так же сыпет таким в логи:

`!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-02-06 16:25:27.402
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at ru.biatech.edt.junit.ruler.TestMethodActionDelegate.dispose(TestMethodActionDelegate.java:66)
	at org.eclipse.ui.internal.PluginAction.disposeDelegate(PluginAction.java:339)
	at org.eclipse.ui.internal.PluginAction.dispose(PluginAction.java:352)
	at org.eclipse.ui.internal.EditorPluginAction.dispose(EditorPluginAction.java:83)
	at org.eclipse.ui.internal.PluginActionBuilder$BasicContribution.disposeActions(PluginActionBuilder.java:498)
	at org.eclipse.ui.internal.ViewerActionBuilder$ViewerContribution.dispose(ViewerActionBuilder.java:158)
	at org.eclipse.ui.internal.ViewerActionBuilder.dispose(ViewerActionBuilder.java:65)
	at org.eclipse.ui.internal.PopupMenuExtender.clearStaticActions(PopupMenuExtender.java:311)
	at org.eclipse.ui.internal.PopupMenuExtender.dispose(PopupMenuExtender.java:504)
	at org.eclipse.ui.part.MultiPageEditorSite.dispose(MultiPageEditorSite.java:219)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorXtextEditorPage.dispose(DtGranularEditorXtextEditorPage.java:233)
	at org.eclipse.ui.forms.editor.FormEditor.dispose(FormEditor.java:410)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.dispose(DtGranularEditor.java:297)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
	at org.eclipse.e4.core.internal.di.InjectorImpl.uninject(InjectorImpl.java:201)
	at org.eclipse.e4.core.internal.di.Requestor.uninject(Requestor.java:177)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:89)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:103)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.removeListenersTo(EclipseContext.java:485)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.uninject(ContextInjectionFactory.java:184)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeRemoveGui(PartRenderingEngine.java:946)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:860)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.removeGui(PartRenderingEngine.java:844)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.subscribeTopicToBeRendered(PartRenderingEngine.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.di.internal.extensions.EventObjectSupplier$DIEventHandler.handleEvent(EventObjectSupplier.java:92)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setToBeRendered(UIElementImpl.java:314)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1331)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.closePart(StackRenderer.java:1182)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$3.close(StackRenderer.java:1042)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1961)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:336)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
`
